"""empty message

Revision ID: 028db3a4dfa5
Revises: ca53335e510b
Create Date: 2023-02-03 21:19:10.727531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028db3a4dfa5'
down_revision = 'ca53335e510b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'content', type_=sa.String(1024), existing_type=sa.Text)
    op.alter_column('author', 'bio', type_=sa.String(1024), existing_type=sa.Text)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_article_association', type_='foreignkey')
    op.drop_constraint(None, 'tag_article_association', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'category_article_association', type_='foreignkey')
    op.drop_constraint(None, 'category_article_association', type_='foreignkey')
    op.drop_constraint(None, 'article_author_association', type_='foreignkey')
    op.drop_constraint(None, 'article_author_association', type_='foreignkey')
    # ### end Alembic commands ###
